apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: docker.io/library/dennissobczk/kaniko:latest
    args: ["--dockerfile=Containerfile",
            "--context=git://github.com/dennissobczak/demo-webapp.git",
            "--context-sub-path=./",
            "--destination=dennissobczak/demo-webapp:latest-linux-amd64",
            "--custom-platform=linux/amd64"
            ] 
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: docker-config
      projected:
        sources:
        - secret:
            name: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
